Update dependencies
techlauncher-mlai-edge-physics/neural_net_physics_tf pull request #2
Opened 2023-08-04 11:08 UTC by Track07-cda

Add some useful dependencies
Fix tensorflowjs no be able to install

2023-08-04 13:01 UTC, ShaneHe023 submitted a review, later dismissed

2023-08-04 14:29 UTC, Lutra-Fs requested changes
Will do further check tmr, better hold this PR now

2023-08-04 14:29 UTC, Lutra-Fs commented on pyproject.toml
> +    "tensorflowjs",
Needs further digging on the tfjs converter, I am aware of the capability with browser

2023-08-05 05:16 UTC, Lutra-Fs requested changes
Add version constraints to reduce the installation time. Also pls change the PR title following commit message convention

2023-08-05 05:16 UTC, Lutra-Fs commented on pyproject.toml
> +    "jupyterlab"
```suggestion
    "tqdm>=4.65.0",
    "matplotlib>=3.7.2",
    "ipykernel>=6.25.0",
    "jupyter>=1.0.0",
    "jupyterlab>=4.0.4",
    "dill>=0.3.7",
    "tensorflow-io-gcs-filesystem==0.31.0",
    "tf2onnx>=1.8.4",
    "onnxruntime>=1.15.1",
    "numpy>=1.24.3",
```

2023-08-05 06:21 UTC, Lutra-Fs approved these changes

2023-08-07 03:57 UTC, merged